{
 "title": "PostgreSQL Exporter Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(pg_stat_database_xact_commit,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "number of cache hits per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"$database\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"$database\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Up Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"$database\"}[5m])\r\n/\r\n(\r\n  rate(pg_stat_database_blks_hit{datname=\"$database\"}[5m])\r\n  + rate(pg_stat_database_blks_read{datname=\"$database\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inserts per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updates per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletes per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size in GB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$database\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed Transactions per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rolled-back Transactions per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}