{
 "title": "Weather Forecast Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "city",
    "query": {
     "query": "label_values(weather_temp_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Coverage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "weather_clouds_percent{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_humidity_percent{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "weather_pressure_hpa{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_wind_deg{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_wind_speed_m_s{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunset",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_sunset_timestamp{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_sunrise_timestamp{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "weather_dew_point_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather Feels Like",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "weather_feels_like_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "weather_temp_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}